# GitHub Pages Configuration for Plug DSL Concepts

title: "Plug DSL Concepts"
description: "Schema-driven game development patterns and innovations by Lost Mountain Games"
author: "Lost Mountain Games"
email: "contact@lostmountain.games"

# Theme configuration
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Navigation and structure
baseurl: "/plug-dsl-concepts"
url: "https://lostmountaingames.github.io"

# SEO and Social
lang: en-US
twitter:
  username: lostmountaingames
  card: summary_large_image

social:
  name: Lost Mountain Games
  links:
    - https://lostmountain.games

# Copyright
copyright: "Copyright © 2025 Lost Mountain Games. All rights reserved."

# Collections
collections:
  syntax:
    output: true
    permalink: /syntax/:name
  architecture:
    output: true
    permalink: /architecture/:name
  performance:
    output: true
    permalink: /performance/:name
  tooling:
    output: true
    permalink: /tooling/:name
  examples:
    output: true
    permalink: /examples/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Lost Mountain Games"
  - scope:
      path: "syntax"
    values:
      layout: "default"
      category: "syntax"
  - scope:
      path: "architecture"
    values:
      layout: "default"
      category: "architecture"
  - scope:
      path: "performance"
    values:
      layout: "default"
      category: "performance"
  - scope:
      path: "tooling"
    values:
      layout: "default"
      category: "tooling"
  - scope:
      path: "examples"
    values:
      layout: "default"
      category: "examples"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - .gitignore
